# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require "bundler"
Bundler.require(:default, :development)

if ENV['COVERAGE']
  require 'simplecov'
  SimpleCov.start
end

Savon.configure do |config|
  config.log = false
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.include Savon::Spec::Macros
end


Savon::Spec::Fixture.path = File.expand_path("../fixtures", __FILE__)

require 'profitbricks'

Savon.configure do |config|
  config.log = false 
  config.log_level = :error
end
HTTPI.log = false
client = Savon::Client.new do |wsdl, http|
  wsdl.endpoint = "https://api.profitbricks.com/1.1"
  wsdl.document = "https://api.profitbricks.com/1.1/wsdl"
  if defined?(RUBY_ENGINE) && RUBY_ENGINE == 'jruby' && !ENV['SSL_CERT_DIR']
    puts "Warning: SSL certificate verification has been disabled"
    http.auth.ssl.verify_mode = :none
  end
end

Profitbricks.configure do |config|
  config.username = "none"
  config.password = "none"
end
Profitbricks.client = client
